// <auto-generated />
namespace Bengo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Practice_Tables_Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Practice_Tables_Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201805050919221_Practice_Tables_Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
